before_script:
- export GRADLE_USER_HOME=~/.gradle

cache:
  paths:
    - node_modules
    - .gradle
    - gradle

stages:
  - setup
  - build
  - deploy


setup:npm:
  stage: setup
  script:
    - ./gradlew -d npmInstall

build:java:
  stage: build
  script:
    - ./gradlew compileJava

build:javaTest:
  stage: build
  script:
    - ./gradlew compileJavaTest

build:npm:
  stage: build
  script:
    - ./gradlew webpack

test:
  stage: deploy
  script:
    - ./gradlew jar

variables:
  GIT_STRATEGY: fetch
