before_script:
- export GRADLE_USER_HOME=${PWD}/.gradle

cache:
  paths:
    - build
    - node_modules

stages:
  - setup
  - build
  - test
  - publish
  - deploy


setup:npm:
  stage: setup
  script:
    - ./gradlew npmInstall

build:java:
  stage: build
  script:
    - ./gradlew compileJava
  artifacts:
    paths:
    - build/libs
    - build/resources/main
    - build/classes/main
    expire_in: 1 day 

build:javaTest:
  stage: build
  script:
    - ./gradlew compileTestJava
  artifacts:
    paths:
    - build/resources/test
    - build/classes/test
    expire_in: 1 day 

build:npm:
  stage: build
  script:
    - ./gradlew webpack
  artifacts:
    paths:
    - build/js
    expire_in: 1 day 

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build:javaTest
    - build:java
  allow_failure: false

publish:
  stage: publish 
  script:
    - ./gradlew build copyDocker
    - docker login --username $REGISTRY_USER --password $REGISTRY_PASSWORD $CI_REGISTRY 
    - docker build -t gitlab.balsen.loc:4901/balsen/kontospring build/docker 
    - docker push gitlab.balsen.loc:4901/balsen/kontospring
  only:
    - master

#deploy:
#  stage: deploy 
#  script:
#  	- kubectl apply
#  only:
#    - master
#variables:
#  GIT_STRATEGY: fetch
