before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

build:
  script:
    - ./gradlew build
  cache:
    paths:
      - mode_modules
      - .gradle
      - gradle

variables:
  GIT_STRATEGY: fetch
