apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: account-controller
  name: account-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-controller
  template:
    metadata:
      labels:
        app: account-controller
    spec:
      containers:
        - image: gitlab.balsen.loc:4901/balsen/accountcontrol/accountcontrol:latest
          imagePullPolicy: Always
          name: account-controller
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
          env:
          - name: PROD
            value: "yes"
      volumes:
      - name: tmp-volume
        emptyDir: {}
      imagePullSecrets:
      - name: regcred
